import html
import json

from fastapi import FastAPI, File, UploadFile
from fastapi.responses import HTMLResponse

from analyze_health import analyze_with_foundry
from sanitizer import sanitize_report


app = FastAPI(
    title="Azure Local Health Analyzer",
    version="1.1.0",
)


@app.get("/", response_class=HTMLResponse)
async def home():
    return """
    <!DOCTYPE html>
    <html>
    <head>
        <title>Azure Local Health Analyzer</title>
        <meta charset="utf-8">

        <style>
            body {
                font-family: Arial, sans-serif;
                max-width: 900px;
                margin: 60px auto;
                padding: 0 20px;
                line-height: 1.5;
            }

            .container {
                border: 1px solid #ddd;
                border-radius: 8px;
                padding: 30px;
            }

            h1 {
                margin-top: 0;
            }

            .description {
                color: #555;
                margin-bottom: 30px;
            }

            input[type=file] {
                margin-bottom: 20px;
            }

            button {
                padding: 10px 20px;
                cursor: pointer;
            }

            .note {
                margin-top: 30px;
                font-size: 0.9em;
                color: #666;
            }

            .privacy-note {
                margin-top: 20px;
                padding: 15px;
                background: #f5f5f5;
                border-left: 4px solid #777;
                font-size: 0.9em;
            }
        </style>
    </head>

    <body>
        <div class="container">

            <h1>Azure Local Health Analyzer</h1>

            <p class="description">
                Upload an Azure Local health report generated by the
                PowerShell health collector.
            </p>

            <form action="/analyze"
                  method="post"
                  enctype="multipart/form-data">

                <input
                    type="file"
                    name="file"
                    accept=".json,application/json"
                    required
                >

                <br>

                <button type="submit">
                    Analyze Health Report
                </button>

            </form>

            <div class="privacy-note">
                Infrastructure identifiers covered by the health-report
                schema are pseudonymized before the report is submitted
                for AI-assisted analysis.
            </div>

            <p class="note">
                AI-assisted analysis is based only on the evidence
                contained in the uploaded health report.
                Results should be reviewed by a qualified engineer.
            </p>

        </div>
    </body>
    </html>
    """


@app.post("/analyze", response_class=HTMLResponse)
async def analyze(file: UploadFile = File(...)):

    try:
        # --------------------------------------------------------------
        # Read and parse the uploaded JSON report.
        # --------------------------------------------------------------
        raw_content = await file.read()

        report = json.loads(
            raw_content.decode("utf-8-sig")
        )

        if not isinstance(report, dict):
            raise ValueError(
                "Invalid Azure Local health report. "
                "The JSON root must be an object."
            )

        # --------------------------------------------------------------
        # Validate the minimum expected report structure.
        # --------------------------------------------------------------
        required_sections = [
            "Metadata",
            "Cluster",
            "AzureLocal",
        ]

        missing_sections = [
            section
            for section in required_sections
            if section not in report
        ]

        if missing_sections:
            raise ValueError(
                "Invalid Azure Local health report. "
                "Missing section(s): "
                + ", ".join(missing_sections)
            )

        # --------------------------------------------------------------
        # Privacy boundary
        #
        # The original uploaded report is used only for local parsing
        # and validation.
        #
        # Infrastructure identifiers covered by the report schema are
        # pseudonymized before the report is passed to the AI analyzer.
        # --------------------------------------------------------------
        sanitized_report = sanitize_report(report)

        # IMPORTANT:
        # Only the sanitized report is submitted to Microsoft Foundry.
        analysis = analyze_with_foundry(
            sanitized_report
        )

        # --------------------------------------------------------------
        # Convert the structured Pydantic result to JSON for display.
        # --------------------------------------------------------------
        analysis_json = analysis.model_dump_json(
            indent=2
        )

        # Escape dynamic content before rendering it in HTML.
        safe_analysis_json = html.escape(
            analysis_json
        )

        safe_filename = html.escape(
            file.filename or "uploaded-report.json"
        )

        return f"""
        <!DOCTYPE html>
        <html>
        <head>
            <title>Azure Local Health Analysis</title>
            <meta charset="utf-8">

            <style>
                body {{
                    font-family: Arial, sans-serif;
                    max-width: 1100px;
                    margin: 50px auto;
                    padding: 0 20px;
                    line-height: 1.5;
                }}

                pre {{
                    background: #f5f5f5;
                    border: 1px solid #ddd;
                    border-radius: 6px;
                    padding: 20px;
                    overflow-x: auto;
                    white-space: pre-wrap;
                }}

                .privacy-note {{
                    margin: 20px 0;
                    padding: 15px;
                    background: #f5f5f5;
                    border-left: 4px solid #777;
                    font-size: 0.9em;
                }}

                a {{
                    display: inline-block;
                    margin-top: 20px;
                }}
            </style>
        </head>

        <body>

            <h1>Azure Local Health Analysis</h1>

            <p>
                File analyzed:
                <strong>{safe_filename}</strong>
            </p>

            <div class="privacy-note">
                Infrastructure identifiers covered by the health-report
                schema were pseudonymized before AI-assisted analysis.
            </div>

            <pre>{safe_analysis_json}</pre>

            <a href="/">
                Analyze another report
            </a>

        </body>
        </html>
        """

    except Exception as error:

        safe_error = html.escape(
            str(error)
        )

        return f"""
        <!DOCTYPE html>
        <html>
        <head>
            <title>Analysis Error</title>
            <meta charset="utf-8">
        </head>

        <body style="
            font-family: Arial, sans-serif;
            max-width: 900px;
            margin: 60px auto;
        ">

            <h1>Unable to analyze health report</h1>

            <p>{safe_error}</p>

            <a href="/">
                Return to Azure Local Health Analyzer
            </a>

        </body>
        </html>
        """